name: youth_card
description: Youth Card Mobile Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.20+38

environment:
  sdk: '>=3.4.0-282.1.beta <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
   #internationalization:
  flutter_localizations:
      sdk: flutter
  intl: ^0.20.2 # for internationalization
  provider: ^6.0.0

  http: ^1.4.0
  #scoped_model: "^1.1.0"
  shared_preferences: ^2.0.5
  #flushbar: ^1.10.4
  #local database:
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  #calendar day list for the calendar - view
  table_calendar: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  #cached images
  cached_network_image: ^3.0.0
  #for getting user location
  geolocator: ^14.0.0
  url_launcher: ^6.0.2
  another_flushbar: ^1.10.17
  flutter_html: ^3.0.0-alpha.2
  flutter_settings_ui:
    git:
      url: https://github.com/Innoventum-oy/flutter_settings_ui
      ref: master
  glob: ^2.0.1
  feedback: ^3.1.0
  queue: ^3.1.0
  file_picker: ^10.1.4
  #for compatibility with ios 14 and flutter_html
  permission_handler: ^12.0.0+1
  date_range_form_field: ^1.0.2
  flutter_rating_bar: ^4.0.0
  wakelock_plus: ^1.3.2
  package_info_plus: ^8.3.0
  qr_code_scanner_plus: ^2.0.10+1
  flutter_lints: ^5.0.0
  geolocator_web: ^4.1.3
  shared_preferences_web: ^2.4.3
  url_launcher_web: ^2.4.1
  path: ^1.9.1
  crypto: ^3.0.6
dependency_overrides:
  date_range_form_field:
    git:
      url: https://github.com/jleinone/date_range_form_field.git


dev_dependencies:
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter

#if you make changes, regenerate with flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: "images/splash.png"
  image: images/squarelogotransparent.png

#if you make changes, regenerate with flutter pub run flutter_launcher_icons:main
flutter_icons:
    android: true
    ios: true
    image_path: "images/icon.png"
  #color: 65afb8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: true #for int
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
